name: Wheels

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.arch }}-python${{ matrix.python }}-alpine${{ matrix.alpine }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8"]
        alpine: ["3.12"]
        arch: ["aarch64", "armhf", "armv7", "amd64", "i386"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.2.0

      - name: Prepare requirements
        run: cat requirements.txt requirements_build.txt > requirements_all.txt

      - name: Build wheels
        uses: openpeerpower/wheels@main
        with:
          tag: ${{ matrix.python }}-alpine${{ matrix.alpine }}
          arch: ${{ matrix.arch }}
          github-token: ${{ secrets.GH_TOKEN }}
          signature: ${{ secrets.GIT_SIGNATURE }}
          apk: "build-base;libffi-dev;openssl-dev;git"
          requirements: "requirements_all.txt"
